name: 'Build and tag a new release'

on: workflow_dispatch

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  npm-build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.*
          cache: npm

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: NPM Build
        run: |
          npm install
          npm run build

      - name: Go builds
        run: ${GITHUB_WORKSPACE}/build_all.sh
